version: "3.8"

services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    ports:
      - "8000:8000"
    env_file: .env

volumes:
  static_volume:
  media_volume:
